Upgrade TSH, add lsp configs.

diff --git a/.local/bin/tsh b/.local/bin/tsh
--- a/.local/bin/tsh
+++ b/.local/bin/tsh
@@ -1,91 +1,115 @@
 #!/bin/bash
 
-# Define files for log, process ID, and reference counting
+# configuration
+SSH_OPTS=(-o "StrictHostKeyChecking=no")
+
+# define files for log, pid, and ref counting
 PIDFILE="/tmp/tsh.pid"
 REFCOUNTFILE="/tmp/tsh.ref"
 LOGFILE="/tmp/tsh.log"
 
-# Function to display usage
-usage() {
-    echo "Usage: $0 [OPTION]..."
-    echo "Connects to a devtunnel instance and runs an SSH-based command based on the OPTIONs passed."
-    echo ""
-    echo "Options:"
-    echo "  --jump, -J       Use SSH -J option with the forwarded port"
-    echo "  --sshuttle, -S   Use sshuttle with the forwarded port"
-    echo "  -h, --help       Display this help and exit"
-    echo ""
-    echo "Without any OPTION, defaults to 'ssh -p forwarded_port localhost'."
-    echo ""
+# devtunnel
+DEVTUNNEL=$(command -v devtunnel)
+
+log() {
+  local msg=$1
+  echo "tsh: $msg" >&2
 }
 
-# Check for help flag
-if [[ " $@ " =~ " -h " ]] || [[ " $@ " =~ " --help " ]]; then
-    usage
-    exit 0
-fi
+# manage refcount
+refcount() {
+  local opt=$1
 
-# Function to ensure devtunnel is installed
-check_devtunnel_installed() {
-  if ! command -v devtunnel &> /dev/null; then
-    echo "tsh: 'devtunnel' is not installed." >&2
+  # initialize refcount
+  if [[ ! -f "$REFCOUNTFILE" ]]; then
+    echo 0 > "$REFCOUNTFILE"
+  fi
+
+  # read current refcount
+  ref=$(<"$REFCOUNTFILE")
+
+  case "$opt" in
+    +)
+      ((ref++))
+      ;;
+
+    -)
+      if [[ $ref -gt 0 ]]; then
+        ((ref--))
+      fi
+      ;;
+
+    0)
+      ref=0
+      ;;
+
+    *)
+      echo $ref
+      ;;
+  esac
+
+  # write refcount
+  echo $ref > "$REFCOUNTFILE"
+}
+
+# checks if devtunnel is installed
+is_devtunnel_installed() {
+  if [[ ! -e $DEVTUNNEL ]]; then
+    log "devtunnel is not installed."
     exit 1
   fi
 }
 
-# Function to check if the PID in PIDFILE is still running as a devtunnel process
-is_process_running() {
-  local pid=$1
-  if [ -z "$pid" ]; then
-    return 1
-  fi
-  if ps -p "$pid" | grep -q "devtunnel"; then
-    return 0
-  else
-    return 1
-  fi
-}
-
-# Start devtunnel and manage reference counting
-start_devtunnel() {
-  if [ ! -f "$REFCOUNTFILE" ]; then
-    echo 0 > "$REFCOUNTFILE"
-  fi
-
-  if [ -f "$PIDFILE" ]; then
+# checks if an instance of devtunnel is already running (by pid)
+is_devtunnel_running() {
+  if [[ -e "$PIDFILE" ]]; then
     pid=$(cat "$PIDFILE")
-    if ! is_process_running "$pid"; then
-      # The process is not running. Reset PIDFILE and REFCOUNT.
-      echo "tsh: Detected stale PID file. Cleaning up." >&2
+
+    # no pid stored
+    if [[ -z "$pid" ]]; then
+      log "Detected empty PID file. Cleaning up."
       rm -f "$PIDFILE"
-      echo 0 > "$REFCOUNTFILE"
+      return 1
+    fi
+
+    # check if pid belong to devtunnel
+    if ps -p "$pid" | grep -q "devtunnel"; then
+      echo "$pid"
+      return 0
+    else
+      log "Detected stale PID file. Cleaning up."
+      rm -f "$PIDFILE"
+      return 1
     fi
   fi
 
-  if [ ! -f "$PIDFILE" ]; then
-    echo "tsh: Starting a new 'devtunnel' instance." >&2
-    devtunnel connect 2>&1 > "$LOGFILE" &
-    echo $! > "$PIDFILE"
-  else
-    echo "tsh: Attaching to existing 'devtunnel' instance." >&2
-  fi
-
-  # Increment the reference count
-  ref=$(<"$REFCOUNTFILE")
-  ((ref++))
-  echo $ref > "$REFCOUNTFILE"
+  return 1
 }
 
-# Extract the forwarded port number
-extract_forward_port() {
-  local timeout=30
-  echo "tsh: Waiting for 'devtunnel' to output the forwarding port information..." >&2 
+# start devtunnel and manage reference counting
+start_devtunnel() {
+  if ! is_devtunnel_running >/dev/null; then
+    log "Starting a new devtunnel instance."
+    devtunnel connect 2>&1 > "$LOGFILE" &
+    echo $! > "$PIDFILE"
+    refcount 0
+  else
+    log "Attaching to existing devtunnel instance."
+  fi
 
-  while [ $timeout -gt 0 ]; do
-    if grep -q "to host port 22" "$LOGFILE"; then
-      local port=$(grep 'SSH: Forwarding from' "$LOGFILE" | grep 'to host port 22' | head -n 1 | sed -r 's/.*127.0.0.1:([0-9]+).*/\1/')
-      echo "tsh: Forwarding port ($port) detected." >&2
-      echo "$port"
+  refcount +
+}
+
+# extract forwarded port number
+get_devtunnel_local_port() {
+  local timeout=30
+  local host_port=$1
+
+  while [[ $timeout -gt 0 ]]; do
+    if grep -q "to host port $host_port" "$LOGFILE"; then
+      local local_port=$(grep "SSH: Forwarding from" "$LOGFILE" | grep "to host port $host_port" | head -n 1 | sed -r "s/.*127.0.0.1:([0-9]+).*/\1/")
+      log "Found port forward $local_port -> $host_port."
+      echo "$local_port"
       return
     else
       sleep 1
@@ -93,70 +117,154 @@ extract_forward_port() {
     fi
   done
 
-  echo "tsh: Timeout while waiting for devtunnel to provide the forwarded port." >&2
+  log "Timeout while waiting for devtunnel to provide the forwarded port."
   return 1
 }
 
-# Function for clean exit
-clean_exit() {
-  if [ -f "$REFCOUNTFILE" ]; then
-    # Decrement the reference count and only stop devtunnel if it reaches 0
-    ref=$(<"$REFCOUNTFILE")
-    ((ref--))
-    echo $ref > "$REFCOUNTFILE"
-
-    if [ "$ref" -eq 0 ]; then
-      if [ -f "$PIDFILE" ]; then
-        pid=$(cat "$PIDFILE")
-        if is_process_running "$pid"; then
-          echo "tsh: No more clients running, closing 'devtunnel' instance."
-          kill "$pid"
-        fi
-        rm -f "$PIDFILE"
-      fi
-      rm -f "$REFCOUNTFILE"
-      rm -f "$LOGFILE"
+# cleanup on exit
+cleanup() {
+  # cleanup when refcount reaches 0
+  refcount -
+  if [[ $(refcount) -eq 0 ]]; then
+    pid=$(is_devtunnel_running)
+    if [[ $? -eq 0 ]]; then
+      log "No more clients running, closing devtunnel instance."
+      kill "$pid"
+      rm -f "$PIDFILE"
     fi
+    rm -f "$REFCOUNTFILE"
+    rm -f "$LOGFILE"
   fi
+
   exit
 }
 
-# Set a trap for clean script termination
-trap 'clean_exit' SIGINT SIGTERM EXIT
+# always cleanup on script termination
+trap 'cleanup' EXIT
 
-# Choose and run the SSH command based on input flags
-run_ssh_command() {
-  local port=$1
-  shift
-  case "$1" in
-    --jump|-J)
-      shift
-      ssh -o "StrictHostKeyChecking no" -J "localhost:$port" "$@"
+
+# command parsing
+parse_command() {
+  local port=$1; shift
+  local opts=""
+  local target=""
+  local cmd=""
+
+  # parse arguments
+  while [[ "$#" -gt 0 ]]; do
+    case $1 in
+      -t|--target)
+        target="$2"
+        shift 2
+        ;;
+
+      proxy|shell|fwd|fs|cmd)
+        cmd="$1"
+        shift
+        break
+        ;;
+
+      *)
+        opts="$opts $1"
+        shift
+        ;;
+    esac
+  done
+
+  # parse target
+  local jump=""
+  local dest=""
+  if [[ -n $target ]]; then
+    if [[ $target == *","* ]]; then
+      # the last host in the comma separated target string is the target
+      jump="localhost:$port,${target%,*}"
+      dest="${target##*,}"
+    else
+      jump="localhost:$port"
+      dest=$target
+    fi
+  fi
+
+  # execute command
+  case $cmd in
+    shell)
+      if [[ -n $jump ]]; then
+        ssh "${SSH_OPTS[@]}" $opts -J $jump $dest $@
+      else
+        ssh "${SSH_OPTS[@]}" $opts -p $port localhost $@
+      fi
       ;;
 
-    --sshuttle|-S)
-      shift
-      sshuttle -e "ssh -o 'StrictHostKeyChecking no'" -r "localhost:$port" "$@"
+    proxy)
+      if [[ -n $jump ]]; then
+        sshuttle -e "ssh ${SSH_OPTS[*]} -J $jump" $opts -x localhost:$port -r $dest $@
+      else
+        sshuttle -e "ssh ${SSH_OPTS[*]}" $opts -x localhost:$port -r localhost:$port $@
+      fi
+      ;;
+    
+    fwd)
+      if [[ -n $jump ]]; then
+        ssh "${SSH_OPTS[@]}" $opts -J $jump -N -L $2:localhost:$1 $dest
+      else
+        ssh "${SSH_OPTS[@]}" $opts -p $port -N -L $2:localhost:$1 localhost
+      fi
       ;;
 
-    *)
-      ssh -o "StrictHostKeyChecking no" -p "$port" localhost "$@"
+    fs)
+      if [[ -n $jump ]]; then
+        sshfs $dest:$@ -o "ssh_command=ssh ${SSH_OPTS[*]} -J $jump" -f $opts
+      else
+        sshfs localhost:$@ -p $port -o "ssh_command=ssh ${SSH_OPTS[*]}" -f $opts
+      fi
+      ;;
+
+    cmd)
+      cmd=$(echo "$@" | host="localhost" port="$port" envsubst)
+      $cmd
       ;;
   esac
 }
 
-main() {
-  check_devtunnel_installed
-  start_devtunnel
-  port=$(extract_forward_port)
+usage() {
+  echo "Usage: tsh [-t hosts] <command> [args...]"
+  echo
+  echo "Options:"
+  echo "  -t, --target <hosts>      Specify target host. Multiple comma-separated hosts"
+  echo "                            are used as jump hosts until the last one. If no target"
+  echo "                            is specified, connection is made to tunnel host."
+  echo
+  echo "  *                         Any other options are passed down to the underlying"
+  echo "                            command."
+  echo
+  echo "Commands:"
+  echo "  shell                     Open an SSH session to target."
+  echo "  proxy                     Forwards traffic over SSH (using sshuttle)."
+  echo "  fwd <remote> <local>      Forwards port to target host."
+  echo "  fs <remote> <local>       Mount remote filesystem."
+  echo "  cmd '<cmd>'               Executes command, interpolating the host and port"
+  echo '                            to the forwarded port as $host and $port.'
+  echo
+  echo "Any additional arguments are passed down to the underlying command."
+  exit 1
+}
 
-  if [ -z "$port" ]; then
-    echo "tsh: Failed to extract the forwarded port. Exiting." >&2
+main() {
+  is_devtunnel_installed
+  start_devtunnel
+  port=$(get_devtunnel_local_port 22)
+
+  if [[ -z "$port" ]]; then
+    log "Exiting."
     exit 1
   fi
 
-  run_ssh_command "$port" "$@"
+  parse_command "$port" "$@"
 }
 
-main "$@"
+if [[ $# -lt 1 ]]; then
+  usage
+  exit 1
+fi
 
+main "$@"
