Upgrade TSH

diff --git a/.local/bin/tsh b/.local/bin/tsh
--- a/.local/bin/tsh
+++ b/.local/bin/tsh
@@ -5,59 +5,25 @@ SSH_OPTS=(-o "StrictHostKeyChecking=no")
 
 # define files for log, pid, and ref counting
 PIDFILE="/tmp/tsh.pid"
-REFCOUNTFILE="/tmp/tsh.ref"
 LOGFILE="/tmp/tsh.log"
 
 # devtunnel
 DEVTUNNEL=$(command -v devtunnel)
 
+# instance counter
+SCRIPT_NAME=$0
+
+instance_count() {
+  let count="$(pgrep -afl bash | grep "$SCRIPT_NAME" | grep -v $$ | wc -l) - 1"
+  echo $count
+}
+
+let INSTANCE_ID="$(instance_count) - 1"
+
+
 log() {
   local msg=$1
-  echo "tsh: $msg" >&2
-}
-
-# manage refcount
-refcount() {
-  local opt=$1
-
-  # initialize refcount
-  if [[ ! -f "$REFCOUNTFILE" ]]; then
-    echo 0 > "$REFCOUNTFILE"
-  fi
-
-  # read current refcount
-  ref=$(<"$REFCOUNTFILE")
-
-  case "$opt" in
-    +)
-      ((ref++))
-      ;;
-
-    -)
-      if [[ $ref -gt 0 ]]; then
-        ((ref--))
-      fi
-      ;;
-
-    0)
-      ref=0
-      ;;
-
-    *)
-      echo $ref
-      ;;
-  esac
-
-  # write refcount
-  echo $ref > "$REFCOUNTFILE"
-}
-
-# checks if devtunnel is installed
-is_devtunnel_installed() {
-  if [[ ! -e $DEVTUNNEL ]]; then
-    log "devtunnel is not installed."
-    exit 1
-  fi
+  echo "tsh:$INSTANCE_ID: $msg" >&2
 }
 
 # checks if an instance of devtunnel is already running (by pid)
@@ -88,16 +54,18 @@ is_devtunnel_running() {
 
 # start devtunnel and manage reference counting
 start_devtunnel() {
+  if [[ ! -e $DEVTUNNEL ]]; then
+    log "devtunnel is not installed."
+    exit 1
+  fi
+
   if ! is_devtunnel_running >/dev/null; then
     log "Starting a new devtunnel instance."
     devtunnel connect 2>&1 > "$LOGFILE" &
     echo $! > "$PIDFILE"
-    refcount 0
   else
     log "Attaching to existing devtunnel instance."
   fi
-
-  refcount +
 }
 
 # extract forwarded port number
@@ -123,16 +91,14 @@ get_devtunnel_local_port() {
 
 # cleanup on exit
 cleanup() {
-  # cleanup when refcount reaches 0
-  refcount -
-  if [[ $(refcount) -eq 0 ]]; then
+  # cleanup if no more instances
+  if [[ $(instance_count) -eq 1 ]]; then
     pid=$(is_devtunnel_running)
     if [[ $? -eq 0 ]]; then
       log "No more clients running, closing devtunnel instance."
       kill "$pid"
       rm -f "$PIDFILE"
     fi
-    rm -f "$REFCOUNTFILE"
     rm -f "$LOGFILE"
   fi
 
@@ -274,7 +240,6 @@ usage() {
 }
 
 main() {
-  is_devtunnel_installed
   start_devtunnel
   port=$(get_devtunnel_local_port 22)
 
